Description of applyIOR
Home > SaliencyToolbox > applyIOR.m
applyIOR
PURPOSE
applyIOR - applies inhibition of return.
SYNOPSIS
function wta = applyIOR(oldWTA,winner,params,varargin)
DESCRIPTION
 applyIOR - applies inhibition of return.
 wta = applyIOR(oldWTA,winner,saliencyParams)
    Applies inihibition of return to the winner-take-all
    network as specified in saliencyParams.IORtype.
 wta = applyIOR(oldWTA,winner,saliencyParams,shapeData)
    For saliencyParams.IORtype = 'shape', the shapeData
    from estimateShape are needed.
 See also diskIOR, shapeIOR, estimateShape, runSaliency, dataStructures.
CROSS-REFERENCE INFORMATION
This function calls:
diskIOR diskIOR - applies disk-shaped inhibition of return.
shapeIOR shapeIOR - applies shape-based inhibition of return.
This function is called by:
batchSaliency batchSaliency - batch processing of lists of images.
guiSaliency guiSaliency - a graphical user interface (GUI) version of the saliency code.
runSaliency runSaliency - compute and display saliency map and fixations.
SOURCE CODE
% applyIOR - applies inhibition of return.
%
% wta = applyIOR(oldWTA,winner,saliencyParams)
%    Applies inihibition of return to the winner-take-all
%    network as specified in saliencyParams.IORtype.
%
% wta = applyIOR(oldWTA,winner,saliencyParams,shapeData)
%    For saliencyParams.IORtype = 'shape', the shapeData
%    from estimateShape are needed.
%
% See also diskIOR, shapeIOR, estimateShape, runSaliency, dataStructures.
% This file is part of the SaliencyToolbox - Copyright (C) 2006-2013
% by Dirk B. Walther and the California Institute of Technology.
% See the enclosed LICENSE.TXT document for the license agreement.
% More information about this project is available at:
% http://www.saliencytoolbox.net
function wta = applyIOR(oldWTA,winner,params,varargin)
switch params.IORtype
  case 'None'
    wta = oldWTA;
  case 'disk'
    wta = diskIOR(oldWTA,winner,params);
  case 'shape'
    if (isempty(varargin))
      error('shapeIOR requires shapeData as an additional argument!');
    end
    if (isempty(varargin{1}))
      wta = diskIOR(oldWTA,winner,params);
    else
      wta = shapeIOR(oldWTA,winner,params,varargin{1});
    end
  otherwise
    error(['Unknown IORtype: ' params.IORtype]);
end