Description of clamp
Home > SaliencyToolbox > clamp.m
clamp
PURPOSE
clamp - clamps data at the top and/or bottom.
SYNOPSIS
function data = clamp(data,bottom,top)
DESCRIPTION
 clamp - clamps data at the top and/or bottom.
 data = clamp(data,bottom,top)
    Sets all values of data that are less than bottom to bottom,
    and all values greater than top to top.
 data = clamp(data,bottom)
    Sets all values less than bottom to bottom.
 data = clamp(data,[],top)
    Sets all values greater than top to top.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
estimateShape estimateShape - estimates the shape of the attended proto-object region.
makeBlueYellowPyramid makeBlueYellowPyramid - creates a blue-yellow opponency pyramid.
makeRedGreenPyramid makeRedGreenPyramid - creates a red-green opponency pyramid
maxNormalizeIterative maxNormalizeIterative - normalize data with the an iterative algorithm.
maxNormalizeLocalMax maxNormalizeLocalMax - normalization based on local maxima.
SOURCE CODE
% clamp - clamps data at the top and/or bottom.
%
% data = clamp(data,bottom,top)
%    Sets all values of data that are less than bottom to bottom,
%    and all values greater than top to top.
%
% data = clamp(data,bottom)
%    Sets all values less than bottom to bottom.
%
% data = clamp(data,[],top)
%    Sets all values greater than top to top.
% This file is part of the SaliencyToolbox - Copyright (C) 2006-2013
% by Dirk B. Walther and the California Institute of Technology.
% See the enclosed LICENSE.TXT document for the license agreement.
% More information about this project is available at:
% http://www.saliencytoolbox.net
function data = clamp(data,bottom,top)
if ~isempty(bottom)
  data(data < bottom) = bottom;
end
if nargin >= 3
  data(data > top) = top;
end