Description of displayImage
Home > SaliencyToolbox > displayImage.m
displayImage
PURPOSE
displayImage - displays an image in a convenient way in the current axes.
SYNOPSIS
function displayImage(img,doNormalize)
DESCRIPTION
 displayImage - displays an image in a convenient way in the current axes.
 displayImage(img) - displays image in the current axis (wrapper for imshow)
    img can be of any numerical type or a logical, and it
        must have two (gray-scale) or three (RGB) dimensions.
    img can be an Image structure (see initializeImage).
    The image is scaled appropriately.
 displayImage(img,doNormalize)
    If doNormalize is 1, the image is maximum-normalized
    (default: 0).
 See also displayMap, displayMaps, showImage, initializeImage, dataStructures.
CROSS-REFERENCE INFORMATION
This function calls:
displayImage displayImage - displays an image in a convenient way in the current axes.
loadImage loadImage - returns the imgData for the Image structure
This function is called by:
displayImage displayImage - displays an image in a convenient way in the current axes.
guiSaliency guiSaliency - a graphical user interface (GUI) version of the saliency code.
plotSalientLocation plotSalientLocation - plots the attended location into an existing figure.
showImage showImage - displays an image in a convenient way.
SOURCE CODE
% displayImage - displays an image in a convenient way in the current axes.
%
% displayImage(img) - displays image in the current axis (wrapper for imshow)
%    img can be of any numerical type or a logical, and it
%        must have two (gray-scale) or three (RGB) dimensions.
%    img can be an Image structure (see initializeImage).
%    The image is scaled appropriately.
%
% displayImage(img,doNormalize)
%    If doNormalize is 1, the image is maximum-normalized
%    (default: 0).
%
% See also displayMap, displayMaps, showImage, initializeImage, dataStructures.
% This file is part of the SaliencyToolbox - Copyright (C) 2006-2013
% by Dirk B. Walther and the California Institute of Technology.
% See the enclosed LICENSE.TXT document for the license agreement.
% More information about this project is available at:
% http://www.saliencytoolbox.net
function displayImage(img,doNormalize)
if (nargin < 2)
  doNormalize = 0;
end
if (isa(img,'struct'))
  displayImage(loadImage(img),doNormalize);
  return;
end
if doNormalize
  imshow(img,[]);
else
  imshow(img);
end
axis image;