Description of loadImage
Home > SaliencyToolbox > loadImage.m
loadImage
PURPOSE
loadImage - returns the imgData for the Image structure
SYNOPSIS
function imgData = loadImage(Image)
DESCRIPTION
 loadImage - returns the imgData for the Image structure
 imgData = loadImage(Image)
    Returns the imgData from one of two sources:
    (1) If Image.data is valid, it is returned after conversion
        to double (if necessary).
    (2) Otherwise, the image is loaded from Image.filename,
        converted to double and returned.
 See also initializeImage, dataStructures.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
contrastModulate contrastModulate - contrast modulates an image according to a map
displayImage displayImage - displays an image in a convenient way in the current axes.
makeBlueYellowPyramid makeBlueYellowPyramid - creates a blue-yellow opponency pyramid.
makeHuePyramid makeHuePyramid - creates a hue distance pyramid.
makeIntensityPyramid makeIntensityPyramid - creates an intensity pyramid.
makeRedGreenPyramid makeRedGreenPyramid - creates a red-green opponency pyramid
showImage showImage - displays an image in a convenient way.
SOURCE CODE
% loadImage - returns the imgData for the Image structure
%
% imgData = loadImage(Image)
%    Returns the imgData from one of two sources:
%    (1) If Image.data is valid, it is returned after conversion
%        to double (if necessary).
%    (2) Otherwise, the image is loaded from Image.filename,
%        converted to double and returned.
%
% See also initializeImage, dataStructures.
% This file is part of the SaliencyToolbox - Copyright (C) 2006-2013
% by Dirk B. Walther and the California Institute of Technology.
% See the enclosed LICENSE.TXT document for the license agreement.
% More information about this project is available at:
% http://www.saliencytoolbox.net
function imgData = loadImage(Image)
if isa(Image.data,'uint8')
  imgData = im2double(Image.data);
elseif isnan(Image.data)
  imgData = im2double(imread(Image.filename));
else
  imgData = Image.data;
end