Description of makeIntensityPyramid
Home > SaliencyToolbox > makeIntensityPyramid.m
makeIntensityPyramid
PURPOSE
makeIntensityPyramid - creates an intensity pyramid.
SYNOPSIS
function intPyr = makeIntensityPyramid(image,type)
DESCRIPTION
 makeIntensityPyramid - creates an intensity pyramid.
 intPyr = makeIntensityPyramid(image,type)
    Creates an intensity pyramid from image.
       image: an Image structure for the input image.
       type: 'dyadic' or 'sqrt2'
 See also makeFeaturePyramids, makeGaussianPyramid, dataStructures.
CROSS-REFERENCE INFORMATION
This function calls:
declareGlobal declareGlobal - declares global variables.
loadImage loadImage - returns the imgData for the Image structure
makeGaussianPyramid makeGaussianPyramid - creates a Gaussian pyramid from map.
This function is called by:
makeFeaturePyramids makeFeaturePyramids - creates a pyramid for featureType.
SOURCE CODE
% makeIntensityPyramid - creates an intensity pyramid.
%
% intPyr = makeIntensityPyramid(image,type)
%    Creates an intensity pyramid from image.
%       image: an Image structure for the input image.
%       type: 'dyadic' or 'sqrt2'
%
% See also makeFeaturePyramids, makeGaussianPyramid, dataStructures.
% This file is part of the SaliencyToolbox - Copyright (C) 2006-2013
% by Dirk B. Walther and the California Institute of Technology.
% See the enclosed LICENSE.TXT document for the license agreement.
% More information about this project is available at:
% http://www.saliencytoolbox.net
function intPyr = makeIntensityPyramid(image,type)
declareGlobal;
im = loadImage(image);
map.origImage = image;
map.label = 'Intensity';
map.data = rgb2gray(im);
map.date = clock;
intPyr = makeGaussianPyramid(map,type);